### ISSUE TITLE
segfault - ringbuffer - really rare occurrence

### ISSUE THREAD

**Issue by jxsl13** [jxsl13/zcatchPlus#1]
```
#0  0x000055555558686c in CRingBufferBase::Allocate (this=0x7ffff6c8ee38, Size=74) at src/engine/shared/ringbuffer.cpp:109
#1  0x000055555556e062 in TStaticRingBuffer<CNetChunkResend, 32768, 0>::Allocate (this=0x7ffff6c8ee38, Size=74) at src/engine/shared/ringbuffer.h:59
#2  0x000055555556d44a in CNetConnection::QueueChunkEx (this=0x7ffff6c8ee20, Flags=1, DataSize=34, pData=0x7fffffffd250, Sequence=210) at src/engine/shared/network_conn.cpp:116
#3  0x000055555556d54d in CNetConnection::QueueChunk (this=0x7ffff6c8ee20, Flags=1, DataSize=34, pData=0x7fffffffd250) at src/engine/shared/network_conn.cpp:142
#4  0x0000555555587b2a in CNetServer::Send (this=0x7ffff6c8ee08, pChunk=0x7fffffffd1a0) at src/engine/shared/network_server.cpp:239
#5  0x000055555558faa0 in CServer::SendMsgEx (this=0x7ffff6a48010, pMsg=0x7fffffffd250, Flags=1, ClientID=-1, System=false) at src/engine/server/server.cpp:678
#6  0x000055555558f956 in CServer::SendMsg (this=0x7ffff6a48010, pMsg=0x7fffffffd250, Flags=1, ClientID=-1) at src/engine/server/server.cpp:639
#7  0x00005555555e04f4 in IServer::SendPackMsg<CNetMsg_Sv_Chat> (this=0x7ffff6a48010, pMsg=0x7fffffffdab0, Flags=1, ClientID=-1) at src/engine/server.h:51
#8  0x00005555555d5594 in CGameContext::SendChat (this=0x555555965390, ChatterClientID=-1, Team=-2, pText=0x7fffffffdbf0 "'MijoyGames' has left the game")
    at src/game/server/gamecontext.cpp:359
#9  0x00005555555cede6 in CPlayer::OnDisconnect (this=0x55555593bba0 <ms_PoolDataCPlayer+2944>, pReason=0x7ffff6cb8b00 "") at src/game/server/player.cpp:284
#10 0x00005555555d7224 in CGameContext::OnClientDrop (this=0x555555965390, ClientID=4, pReason=0x7ffff6cb8b00 "") at src/game/server/gamecontext.cpp:964
#11 0x0000555555590440 in CServer::DelClientCallback (ClientID=4, pReason=0x7ffff6cb8b00 "", pUser=0x7ffff6a48010) at src/engine/server/server.cpp:853
#12 0x000055555558711a in CNetServer::Drop (this=0x7ffff6c8ee08, ClientID=4, pReason=0x7ffff6cb8b00 "") at src/engine/shared/network_server.cpp:63
#13 0x0000555555587311 in CNetServer::Update (this=0x7ffff6c8ee08) at src/engine/shared/network_server.cpp:84
#14 0x0000555555592d32 in CServer::PumpNetwork (this=0x7ffff6a48010) at src/engine/server/server.cpp:1385
#15 0x0000555555593a97 in CServer::Run (this=0x7ffff6a48010) at src/engine/server/server.cpp:1627
#16 0x0000555555596aa6 in main (argc=1, argv=0x7fffffffe348) at src/engine/server/server.cpp:2438



######################## FULL ##########################

#0  0x000055555558686c in CRingBufferBase::Allocate (this=0x7ffff6c8ee38, Size=74) at src/engine/shared/ringbuffer.cpp:109
        pNewItem = 0x7ffff6c8ef28
        WantedSize = 120
        pBlock = 0x7ffff6c8eeb0
#1  0x000055555556e062 in TStaticRingBuffer<CNetChunkResend, 32768, 0>::Allocate (this=0x7ffff6c8ee38, Size=74) at src/engine/shared/ringbuffer.h:59
No locals.
#2  0x000055555556d44a in CNetConnection::QueueChunkEx (this=0x7ffff6c8ee20, Flags=1, DataSize=34, pData=0x7fffffffd250, Sequence=210) at src/engine/shared/network_conn.cpp:116
        pResend = 0x7fffffffd110
        pChunkData = 0x7ffff6c96fbd "es'"
        Header = {m_Flags = 1, m_Size = 34, m_Sequence = 210}
#3  0x000055555556d54d in CNetConnection::QueueChunk (this=0x7ffff6c8ee20, Flags=1, DataSize=34, pData=0x7fffffffd250) at src/engine/shared/network_conn.cpp:142
No locals.
#4  0x0000555555587b2a in CNetServer::Send (this=0x7ffff6c8ee08, pChunk=0x7fffffffd1a0) at src/engine/shared/network_server.cpp:239
        Flags = 1
#5  0x000055555558faa0 in CServer::SendMsgEx (this=0x7ffff6a48010, pMsg=0x7fffffffd250, Flags=1, ClientID=-1, System=false) at src/engine/server/server.cpp:678
        i = 0
        Packet = {m_ClientID = 0, m_Address = {type = 0, ip = '\000' <repeats 15 times>, port = 0}, m_Flags = 1, m_DataSize = 34, m_pData = 0x7fffffffd250}
#6  0x000055555558f956 in CServer::SendMsg (this=0x7ffff6a48010, pMsg=0x7fffffffd250, Flags=1, ClientID=-1) at src/engine/server/server.cpp:639
No locals.
#7  0x00005555555e04f4 in IServer::SendPackMsg<CNetMsg_Sv_Chat> (this=0x7ffff6a48010, pMsg=0x7fffffffdab0, Flags=1, ClientID=-1) at src/engine/server.h:51
        Packer = {<CPacker> = {
            m_aBuffer = "\006\000@'MijoyGames' has left the game\000\377\377\377\177\000\000 \330\377\377\377\177\000\000\020\330\377\377\377\177\000\000\024#jUUU\000\000\240\331\377\377\377\177\000\000\000\000\000\000\000\000\000\000\036\000\000\000\000\000\000\000\271\064\334\366\377\177", '\000' <repeats 14 times>, "UU\000\000\000\000\000\000UU\000\00

0\377\377\377\377\377\377\377\377x\323\377\377\377\177\000\000\000\000\000\000UU\000\000\240\323\377\377\377\177\000\000 ", '\000' <repeats 19 times>, "UU\000\000\000\000\000\000\377\177\000\000\377\377\377\377\377\377\377\377\000\000\000\000\000\000\000\000"..., m_pCurrent = 0x7fffffffd272 "\377\377\377\177",
            m_pEnd = 0x7fffffffda50 "r\322\377\377\377\177", m_Error = 0}, <No data fields>}
#8  0x00005555555d5594 in CGameContext::SendChat (this=0x555555965390, ChatterClientID=-1, Team=-2, pText=0x7fffffffdbf0 "'MijoyGames' has left the game")
    at src/game/server/gamecontext.cpp:359
        Msg = {m_Team = 0, m_ClientID = -1, m_pMessage = 0x7fffffffdbf0 "'MijoyGames' has left the game"}
        aBuf = "*** 'MijoyGames' has left the game\000\377\377\177\000\000\237\037jUUU\000\000Rt\214\000\000\002\000\000\360\333\377\377\377\177\000\000 \000\000\000\060\000\000\000\340\333\377\377\377\177\000\000 \333\377\377\377\177\000\000\364\355\306\366\036\000\000\000p\333\377\377\377\177\000\000\277Yq\035\000\000\000\000P\333\377\377\377\177\000\000\360l\254\366\377\177\000\000\n\347\000\000\000\000\000\000c\037\316\364\357>A\000\001\000\000\000\200\003\000\000\200\205\223UUU\000\000\220\333\377\377\377\177\000\000\301\062[UUU\000\000\220\333\377\377\377\177\000\000\200\205\223UUU\000\000\240\333\377\377\377\177\000\000"...
#9  0x00005555555cede6 in CPlayer::OnDisconnect (this=0x55555593bba0 <ms_PoolDataCPlayer+2944>, pReason=0x7ffff6cb8b00 "") at src/game/server/player.cpp:284
        aBuf = "'MijoyGames' has left the game\000\000XϧUUU\000\000X\214\237UUU\000\000P\334\377\377\377\177\000\000\067\217bUUU\000\000P\334\377\377\377\177\000\000X\363\256UUU\000\000`\334\377\377\000\000\000\000X\214\237UUU\000\000\220\334\377\377\377\177\000\000\246\267bUUU\000\000\260\334\377\377\377\177\000\000X\363\256UUU\000\000\027\000\000\000\000\000\000\000X\214\237UUU\000\000X\363\256UUU\000\000\000\000\000\000\000\000\000\000\260\334\377\377\377\177\000\000\301\326XUUU\000\000\000\355\236UUU\000\000X\363\256UUU\000\000\060\335\377\377\377\177\000\000l"...
#10 0x00005555555d7224 in CGameContext::OnClientDrop (this=0x555555965390, ClientID=4, pReason=0x7ffff6cb8b00 "") at src/game/server/gamecontext.cpp:964
No locals.
#11 0x0000555555590440 in CServer::DelClientCallback (ClientID=4, pReason=0x7ffff6cb8b00 "", pUser=0x7ffff6a48010) at src/engine/server/server.cpp:853
        pThis = 0x7ffff6a48010
        aAddrStr = "85.61.164.155:56503\000\000\000\000\000\240\n\313\366\377\177\000\000\340\337\377\377\377\177\000\000\304\334VUUU\000"
        aBuf = "client dropped. cid=4 addr=85.61.164.155:56503 reason=''\000\337\377\377\377\177\000\000\340\337\377\377\002\000\000\000\001\000\000\000\000\000\000\000\240~VUUU\000\000@\343\377\377\377\177\000\000\000\337\377\377\377\177\000\000f\031\347\366\377\177\000\000\345\326\377\377\377\177\000\000\a\000\000\000\000\000\000\000\020\337\377\377\377\177\000\000\340\375\231UUU\000\000Rt\214\000\000\000\000\000\221m\207\003\000\000\000\000p\340\377\377\377\177\000\000P\337\377\377\377\177\000\000\006\254\377\367\377\177\000\

000\200\337\377\377\377\177\000\000\202`\321\366\002\000\000\000"...
#12 0x000055555558711a in CNetServer::Drop (this=0x7ffff6c8ee08, ClientID=4, pReason=0x7ffff6cb8b00 "") at src/engine/shared/network_server.cpp:63
No locals.
#13 0x0000555555587311 in CNetServer::Update (this=0x7ffff6c8ee08) at src/engine/shared/network_server.cpp:84
        i = 4
        Now = 9204818059207
#14 0x0000555555592d32 in CServer::PumpNetwork (this=0x7ffff6a48010) at src/engine/server/server.cpp:1385
        Packet = {m_ClientID = -8080, m_Address = {type = 32767, ip = "@B\017\000\000\000\000\000\307\037\351)_\b\000", port = 32784}, m_Flags = 32767, m_DataSize = -153699672,
          m_pData = 0x7ffff6c8ee08}
#15 0x0000555555593a97 in CServer::Run (this=0x7ffff6a48010) at src/engine/server/server.cpp:1627
        t = 9204818059206
        NewTicks = 0
        ReportTime = 9204820723376
        ReportInterval = 3
        BindAddr = {type = 11, ip = '\000' <repeats 15 times>, port = 8303}
        aBuf = "version 0.6 626fce9a778df4d4\000de'\000fYUUU\000\000\002", '\000' <repeats 95 times>, "\020\000\000\000\060\000\000\000\000\342\377\377\377\177\000\000@\341\377\377\377\177\000\000/\321\377\377\377\177\000\000\037\000\000\000\002", '\000' <repeats 28 times>...
        pDisconnectReason = 0x0
#16 0x0000555555596aa6 in main (argc=1, argv=0x7fffffffe348) at src/engine/server/server.cpp:2438
        pServer = 0x7ffff6a48010
        pKernel = 0x555555960f10
        pEngine = 0x555555961830
        pEngineMap = 0x555555963d00

#14 0x0000555555592d32 in CServer::PumpNetwork (this=0x7ffff6a48010) at src/engine/server/server.cpp:1385
        Packet = {m_ClientID = -8080, m_Address = {type = 32767, ip = "@B\017\000\000\000\000\000\307\037\351)_\b\000", port = 32784}, m_Flags = 32767, m_DataSize = -153699672,
          m_pData = 0x7ffff6c8ee08}
#15 0x0000555555593a97 in CServer::Run (this=0x7ffff6a48010) at src/engine/server/server.cpp:1627
        t = 9204818059206
        NewTicks = 0
        ReportTime = 9204820723376
        ReportInterval = 3
        BindAddr = {type = 11, ip = '\000' <repeats 15 times>, port = 8303}
        aBuf = "version 0.6 626fce9a778df4d4\000de'\000fYUUU\000\000\002", '\000' <repeats 95 times>, "\020\000\000\000\060\000\000\000\000\342\377\377\377\177\000\000@\341\377\377\377\177\000\000/\321\377\377\377\177\000\000\037\000\000\000\002", '\000' <repeats 28 times>...
        pDisconnectReason = 0x0
#16 0x0000555555596aa6 in main (argc=1, argv=0x7fffffffe348) at src/engine/server/server.cpp:2438
        pServer = 0x7ffff6a48010
        pKernel = 0x555555960f10
        pEngine = 0x555555961830
        pEngineMap = 0x555555963d00
---Type <return> to continue, or q <return> to quit---
        pGameServer = 0x555555965390
        pConsole = 0x5555559646e0
        pEngineMasterServer = 0x55555599fde0
        pStorage = 0x5555559a03d0
        pConfig = 0x5555559a29f0

```

**Comment by jxsl13** [comment]
has not occurred again after changing the orders on disconnecting.
